
services:
  postgres:
    image: postgres:latest
    container_name: tbm-postgres
    restart: always
    environment:
      POSTGRES_DB: ${DatabaseName:-TBM}
      POSTGRES_USER: ${DatabaseUsername}
      POSTGRES_PASSWORD: ${DatabasePassword}
    expose:
      - "${DatabasePort:-5432}"
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DatabaseUsername} -d ${DatabaseName:-TBM}" ]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - backend

  dotnet:
    #image: ghcr.io/martinwillu/tbm/backend:main
    container_name: dotnet
    build:
      context: ./backend
      dockerfile: ./TheForbiddenFridge/Dockerfile
    env_file:
      - .env
    expose:
      - "5200"
    ports: 
       - "${FRONTEND_PORT:-80}:80"
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - frontend
      - backend
    restart: unless-stopped

  vite:
    #image: ghcr.io/martinwillu/tbm/frontend:main
    container_name: vite
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    env_file:
      - .env
    network_mode: "service:dotnet"
    depends_on:
      - dotnet 
    restart: unless-stopped
    
volumes:
  postgres_data:

networks:
  frontend:
    driver: bridge
    driver_opts:
      com.docker.network.bridge.host_binding_ipv4: "127.0.0.1"
  backend:
    driver: bridge
    external: false